// showcase-react/src/pages/breadcrumbs.js
import React, { useEffect, useRef } from 'react';

const Breadcrumbs = () => {
  const ref = useRef(null);
  const data = [
    { text: 'Abuelo', link: 'LinkAbuelo' },
    { text: 'padre', link: 'LinkPadre', dataAutomation: 'auto-link-padre' },
    { text: 'hijo' },
  ];

  useEffect(() => {
    ref.current.paths = data;
  }, [data]);

  return (
    <div>
      <h2>Breadcrumbs</h2>
      <st-core-breadcrumbs ref={ref}></st-core-breadcrumbs>
    </div>
  );
};

export default Breadcrumbs;

// showcase-angular/src/app/components/breadcrumbs/breadcrumbs.component.ts
import { Component, OnInit } from '@angular/core';
import { IBreadcrumbItem } from 'lighthouse-ui-core-stencil/dist/types/components/breadcrumbs/models/breadcrumbs.interface';

@Component({
  selector: 'app-breadcrumbs',
  templateUrl: './breadcrumbs.component.html',
})
export class BreadcrumbsComponent implements OnInit {
  data: IBreadcrumbItem[] = [
    { text: 'Abuelo', link: 'LinkAbuelo' },
    { text: 'padre', link: 'LinkPadre', dataAutomation: 'auto-link-padre' },
    { text: 'hijo' },
  ];

  constructor() {}

  ngOnInit() {}
}

<div class="col-12">
  <h4 class="pt-3 pb-3">Breadcrumbs component</h4>

  <h5>Example</h5>

  <st-core-breadcrumbs [paths]="this.data"></st-core-breadcrumbs>

  <hr />

  <h5>Data</h5>

  <h6>Input</h6>y

  <ul>
    <li>
      [data] :
      <pre>{{ data | json }}</pre>
    </li>
  </ul>

  <h6>Output</h6>

</div>
